"""update user table

Revision ID: 6afea8b902fb
Revises: 8dc9de712e34
Create Date: 2024-06-18 20:55:22.848167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afea8b902fb'
down_revision: Union[str, None] = '8dc9de712e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'role')
    # ### end Alembic commands ###
