"""update client table

Revision ID: 8dc9de712e34
Revises: ac07e9cab465
Create Date: 2024-06-18 18:31:58.970340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc9de712e34'
down_revision: Union[str, None] = 'ac07e9cab465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('cpf', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_cpf'), 'clients', ['cpf'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_cpf'), table_name='clients')
    op.drop_column('clients', 'cpf')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
