"""create tables order and order item

Revision ID: b557831fd78b
Revises: 154c904a7a15
Create Date: 2024-06-19 13:28:49.378987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b557831fd78b'
down_revision: Union[str, None] = '154c904a7a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('subtotal', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'subtotal')
    # ### end Alembic commands ###
