"""create subtotal in table order

Revision ID: c9ba7a25d5bf
Revises: beb4b77ecac8
Create Date: 2024-06-19 14:04:59.493484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ba7a25d5bf'
down_revision: Union[str, None] = 'beb4b77ecac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False, default=0.0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
